apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: noetlsparks.compute.noetl.com
spec:
  group: compute.noetl.com
  names:
    kind: NoetlSpark
    plural: noetlsparks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            spark:
              items:
                properties:
                  class:
                    type: string
                  confs:
                    items:
                      type: string
                    type: array
                  image:
                    type: string
                  jar:
                    type: string
                  name:
                    type: string
                  priority:
                    format: int64
                    type: integer
                  resources:
                    type: string
                type: object
              type: array
          type: object
        status:
          properties:
            message:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
