apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - jobss
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - compute.noetl.com
  resources:
  - noetlsparks
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
