apiVersion: compute.noetl.com/v1beta1
kind: NoetlSpark
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: noetlspark-transform
spec:
  spark:

  - name: "extract-asset"
    job-type: subcrribe to kafta
    resources: "60%"
    priority: 1
    class: com.qualys.datalake.pipelines.Loader
    image: art-hq.intranet.qualys.com:5001/datalake/spark-hadoop-integrator:0.1.1
    jar: "local:///opt/spark/jars/integrator-assembly-0.1.1-SNAPSHOT.jar"
    confs:
      - noetl/asset

  - name: "extract-asset-host"
    resources: "30%"
    priority: 2
    class: com.qualys.datalake.pipelines.Loader
    image: art-hq.intranet.qualys.com:5001/datalake/spark-hadoop-integrator:0.1.1
    jar: "local:///opt/spark/jars/integrator-assembly-0.1.1-SNAPSHOT.jar"
    confs:
      - noetl/asset-host

  - name: "extract-host-control"
    resources: "10%"
    priority: 2
    class: com.qualys.datalake.pipelines.Loader
    image: art-hq.intranet.qualys.com:5001/datalake/spark-hadoop-integrator:0.1.1
    jar: "local:///opt/spark/jars/integrator-assembly-0.1.1-SNAPSHOT.jar"
    confs:
      - noetl/asset-tag
